---

- name: Converge
  hosts: all
  become: true

  vars:
    openwisp2_network_topology: true
    openwisp2_controller_pip: "https://github.com/pandafy/openwisp-controller/tarball/fix-tests"

  pre_tasks:
    - name: Update apt cache
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: Remove the .dockerenv file
      file:
        path: /.dockerenv
        state: absent

  roles:
    - role: ansible-openwisp2
